Fixed host binary

diff --git a/.docker/host/bin/deploy b/.docker/host/bin/deploy
--- a/.docker/host/bin/deploy
+++ b/.docker/host/bin/deploy
@@ -1,6 +1,7 @@
 #!/bin/bash
 
-set -e;
+# set -e;
+# set -x;
 
 # Define color variables
 RED='\033[0;31m'     # Red
@@ -39,11 +40,10 @@ title2 () {
   echo -e "${BOLD_WHITE}$1${NC}"
 }
 
-
-cleanup_ssh() {
-    if [ -n "$SSH_PID" ]; then
-        echo "Killing SSH tunnel with PID $SSH_PID"
-        kill ${SSH_PID}
+check_command() {
+    if [ $? -ne 0 ]; then
+        echo -e "${RED}Error: $1 failed!${NC}"
+        exit 1
     fi
 }
 
@@ -78,11 +78,28 @@ MAKEFILE=${MAKE_FILE:-Makefile.cicd}
 STAGING_URL="${STAGING_USER}@${STAGING_HOST} -p ${STAGING_PORT}"
 SSH_TUNNEL="-L 5000:registry:5000 $STAGING_URL"
 
+function cleanup()
+{
+  if [ -n "$SSH_PID" ]; then
+    echo "Killing SSH tunnel with PID $SSH_PID"
+    kill ${SSH_PID}
+  fi
+
+  if [ "$(docker image ls | grep "localhost:5000")" ]; then
+    echo "Clean up images..."
+    docker image ls | grep "localhost:5000" | awk '{print $3}' | xargs docker rmi -f;
+  fi
+}
+
+trap cleanup EXIT
+
 title1 "Deploying $VERSION ($GIT_REPO) to staging..."
 git clone --depth=1 ${GIT_REPO} --branch=${BRANCH} ${APP_ROOT} || :;
+check_command "Repository cloning"
 
 cd ${APP_ROOT} || exit;
-git fetch --all  && git pull --all;
+git fetch --all  && git pull --ff;
+check_command "Repository cloning"
 
 # Check if the git commands were successful
 if [ $? -eq 0 ]; then
@@ -94,18 +111,6 @@ if [ $? -eq 0 ]; then
   fi
 fi
 
-function cleanup()
-{
-  cleanup_ssh
-
-  if [ "$(docker image ls | grep "localhost:5000")" ]; then
-    echo "Clean up images..."
-    docker image ls | grep "localhost:5000" | awk '{print $3}' | xargs docker rmi -f;
-  fi
-}
-
-trap cleanup EXIT
-
 if [ ! -f "$MAKEFILE" ]; then
     echo -e "${RED}Makefile not found: $MAKEFILE (in: $APP_ROOT)${NC}"
     exit 1
@@ -115,10 +120,7 @@ title1 "Creating registry tunnel ..."
 title2 "ssh $SSH_TUNNEL -N -f"
 
 ssh $SSH_TUNNEL -N -f
-if [ ! $? -eq 0 ]; then
- echo -e "${RED}Failed to create SSH tunnel.${NC}"
- exit 1
-fi
+check_command "SSH tunnel"
 
 SSH_PID=$(pgrep -f "ssh $SSH_TUNNEL")
 
@@ -128,11 +130,15 @@ if [ -f "$MAKEFILE" ]; then
   title2 "Makefile found! Using it ..."
 
   make -f ${MAKE_FILE:-Makefile.cicd} deploy VERSION=$VERSION
+  check_command "Make deploy"
 else
   title2 "Runnig docker compose commands..."
 
 	docker compose pull --quiet
+  check_command "Docker pull"
+
 	docker compose up --no-build -d
+  check_command "Dockre up"
 
 fi
 
