Improved test-containers process

diff --git a/.docker/host/bin/deploy b/.docker/host/bin/deploy
--- a/.docker/host/bin/deploy
+++ b/.docker/host/bin/deploy
@@ -18,9 +18,16 @@ cleanup_ssh() {
 
 # Exit on missing argument
 if [ -z "$1" ]; then
+    echo -e "${RED}Error: Branch name is missing!${NC}"
+    exit 1
+fi
+
+# Exit on missing argument
+if [ -z "$2" ]; then
     echo -e "${RED}Error: Build name is missing!${NC}"
     exit 1
 fi
+
 
 # ENVIRONEMTN VARS
 export ROOT="$(pwd)"
@@ -41,7 +48,7 @@ echo "Cloning ($GIT_REPO) ..."
 git clone ${GIT_REPO} --branch=${BRANCH} ${APP_ROOT} || :;
 
 cd ${APP_ROOT} || exit;
-git fetch --all  && git upll --all;
+git fetch --all  && git pull --all;
 
 function cleanup()
 {
diff --git a/.docker/staging/bin/stage b/.docker/staging/bin/stage
--- a/.docker/staging/bin/stage
+++ b/.docker/staging/bin/stage
@@ -82,19 +82,19 @@ echo -e "\n${GREEN}Ready! Build directory ($BUILD_DIR) created ...${NC}\n"
 
 ssh-keyscan staging >> /home/cicd/.ssh/known_hosts;
 
-# As long as the SSH tunnel isnt working:
-docker run -d -p 5000:5000 --name local-registry registry:2
+## As long as the SSH tunnel isnt working:
+#docker run -d -p 5000:5000 --name local-registry registry:2
 
-# echo -e "\n${GREEN}Creating registry tunnel ...${NC}\n"
-# echo "ssh $SSH_TUNNEL -N -f"
+echo -e "\n${GREEN}Creating registry tunnel ...${NC}\n"
+echo "ssh $SSH_TUNNEL -N -f"
 
-# ssh $SSH_TUNNEL -N -f
-# if [ ! $? -eq 0 ]; then
-#   echo -e "${RED}Failed to create SSH tunnel.${NC}"
-#   exit 1
-# fi
+ssh $SSH_TUNNEL -N -f
+if [ ! $? -eq 0 ]; then
+ echo -e "${RED}Failed to create SSH tunnel.${NC}"
+ exit 1
+fi
 
-# SSH_PID=$(pgrep -f "ssh $SSH_TUNNEL")
+SSH_PID=$(pgrep -f "ssh $SSH_TUNNEL")
 
 
 # tail -f /dev/null
